FROM python:3.10-slim

# Install ffmpeg
RUN apt-get update && apt-get install -y ffmpeg

# Copy project
WORKDIR /app
COPY . .

# Install Python deps
RUN pip install -r requirements.txt

# Run bot
CMD ["python", "bot.py"]
